routes/web.php
<?php

use App\Http\Controllers\BoatController;
use App\Http\Controllers\CarController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\VillaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::any('/', [HomeController::class,'index_view']);
Route::get('get-a-room-api-fetch', [HomeController::class,'getARoomApiFetch']);
Route::get('get-a-room-seed', [HomeController::class,'getARoomSeed']);
Route::get('home', [HomeController::class,'index_view'])->name('home')->middleware('auth');
Route::get('login', [HomeController::class,'login_view'])->name('login.view')->middleware('guest');
Route::post('login', [HomeController::class,'login'])->name('login.store')->middleware('guest');
Route::get('signup', [HomeController::class,'signup_view'])->name('signup.view')->middleware('guest');
Route::post('signup', [HomeController::class,'signup_store'])->name('signup.store');
Route::get('logout', [HomeController::class,'logout'])->name('logout');


Route::group(['middleware' => 'auth',], function(){
    Route::get('dashboard', [HomeController::class,'index_view'])->name('dashboard.view')->middleware('auth');

    Route::group(['prefix' => 'car','as' => 'car.',], function(){
        Route::group(['prefix' => 'feature','as' => 'feature.',], function(){
            Route::get('create', [CarController::class,'createCarFeatureView'])->name('create.view');
            Route::post('store', [CarController::class,'createCarFeature'])->name('create');
            Route::get('list', [CarController::class,'listCarFeature'])->name('list.view');
        });
        Route::get('create', [CarController::class,'createView'])->name('create.view');
        Route::post('store', [CarController::class,'create'])->name('create');
        Route::post('import', [CarController::class,'import'])->name('import');
        Route::get('list', [CarController::class,'listView'])->name('list.view');
        Route::get('delete', [CarController::class,'delete'])->name('delete');
    });

    Route::group(['prefix' => 'boat','as' => 'boat.',], function(){
        Route::get('create', [BoatController::class,'createView'])->name('create.view');
        Route::post('store', [BoatController::class,'create'])->name('create');
        Route::post('import', [BoatController::class,'import'])->name('import');
        Route::get('list', [BoatController::class,'listView'])->name('list.view');
        Route::get('delete', [BoatController::class,'delete'])->name('delete');
    });

    Route::group(['prefix' => 'villa','as' => 'villa.',], function(){
        Route::get('create', [VillaController::class,'createView'])->name('create.view');
        Route::post('store', [VillaController::class,'create'])->name('create');
//        Route::post('import', [BoatController::class,'import'])->name('import');
        Route::get('list', [VillaController::class,'listView'])->name('list.view');
//        Route::get('delete', [BoatController::class,'delete'])->name('delete');
    });



});

app/Models/Villa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Villa extends Model
{
    use HasFactory;
    protected $appends=['media'];
    public function getMediaAttribute()
    {
        $returnable=[];
        $returnable['images']=Media::where(['reference_code'=>config('app.VILLA_IMAGES'),'refrence_id'=>$this->id])->get();
        return $returnable;
    }
}

app/Http/Controllers/VillaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\MediaService;
use App\Models\City;
use App\Models\Country;
use App\Models\State;
use App\Models\Villa;
use Illuminate\Http\Request;

class VillaController extends Controller
{
    function createView()
    {
        $countries=Country::all('name','id');
//        $states=State::all('name','id');
//        $cities=City::all('name','id');
        foreach ($countries as $country) {
            $country['value']=$country->name;
        }
//        foreach ($states as $s) {
//            $s['value']=$s->name;
//        }
//        foreach ($cities as $c) {
//            $c['value']=$c->name;
//        }
        return view('villa.create',['countries'=>$countries,]);
    }
    function create(Request $request)
    {
       $validation=$request->validate([
           'name'=>'required',
           'country'=>'required',
           'state'=>'required',
           'city'=>'required'
       ]);

       $countryId = json_decode($request->country, true)[0]['id'];
       if(!empty($request->listingAmenities)){
        $listingAmenities = collect(json_decode($request->listingAmenities))->pluck('value');
       }else{
        $listingAmenities = NULL;
       }

       $villa=new Villa();
       $villa->name=$request->name;
       $villa->description=$request->description;
       $villa->houseRules=$request->houseRules;
       $villa->country= $countryId;
       $villa->state= $request->state;
       $villa->city= $request->city;
       $villa->countryCode='en'; //Static data
       $villa->zipcode=$request->zipcode;
       $villa->price=$request->price;
       $villa->starRating=$request->starRating;
       $villa->weeklyDiscount=$request->weeklyDiscount;

       $villa->monthlyDiscount=$request->monthlyDiscount;
       $villa->address=$request->address;
       $villa->lat=$request->lat;
       $villa->lng=$request->lng;

       $villa->roomType= 'entire_home'; //Static data
       $villa->language='en'; //Static data
       $villa->currencyCode='US'; //Static data
       $villa->listingAmenities= $listingAmenities;

       if (!$villa->save()){
           return redirect()->back()->with('error',config('app.NEGATIVE_MESSAGE'));
       }

       if ($request->hasFile('listingImages')){
           $ms=new MediaService();
           foreach ($request->listingImages as $image){
               $ms->upload($image,'villas',config('app.VILLA_IMAGES'),$villa->id);
           }
       }
        return redirect()->route('villa.list.view')->with('success',config('app.POSITIVE_MESSAGE'));
    }
    function listView()
    {
        $villas = Villa::get();
        return view('villa.index', compact('villas'));
    }
}

resources/views/villa/index.blade.php
@extends('layout.panel')
@section('breadcrumb')
    <li class="breadcrumb-item pe-3"><a href="{{route('boat.list.view')}}" class="pe-3">Villa</a></li>
@endsection
@section('content')
    <!--begin::Post-->
    <div class="row">
        <div class="col">
            <div class="card mb-5 mb-xl-8">
                <!--begin::Header-->
                <div class="card-header border-0 pt-5">
                    <h3 class="card-title align-items-start flex-column">
                        <span class="card-label fw-bolder fs-3 mb-1">List Villa</span>
                        <span class="text-muted mt-1 fw-bold fs-7">Over  Villa</span>
                    </h3>
                    <div class="card-toolbar">
{{--                        <!--begin::Menu-->--}}
{{--                        <button type="button" class="btn btn-sm btn-icon btn-color-primary btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">--}}
{{--                            <!--begin::Svg Icon | path: icons/duotune/general/gen024.svg-->--}}
{{--                            <span class="svg-icon svg-icon-2">--}}
{{--													<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">--}}
{{--														<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">--}}
{{--															<rect x="5" y="5" width="5" height="5" rx="1" fill="currentColor" />--}}
{{--															<rect x="14" y="5" width="5" height="5" rx="1" fill="currentColor" opacity="0.3" />--}}
{{--															<rect x="5" y="14" width="5" height="5" rx="1" fill="currentColor" opacity="0.3" />--}}
{{--															<rect x="14" y="14" width="5" height="5" rx="1" fill="currentColor" opacity="0.3" />--}}
{{--														</g>--}}
{{--													</svg>--}}
{{--												</span>--}}
{{--                            <!--end::Svg Icon-->--}}
{{--                        </button>--}}
{{--                        <!--begin::Menu 2-->--}}
{{--                        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-bold w-200px" data-kt-menu="true">--}}
{{--                            <!--begin::Menu item-->--}}
{{--                            <div class="menu-item px-3">--}}
{{--                                <div class="menu-content fs-6 text-dark fw-bolder px-3 py-4">Quick Actions</div>--}}
{{--                            </div>--}}
{{--                            <!--end::Menu item-->--}}
{{--                            <!--begin::Menu separator-->--}}
{{--                            <div class="separator mb-3 opacity-75"></div>--}}
{{--                            <!--end::Menu separator-->--}}
{{--                            <!--begin::Menu item-->--}}
{{--                            <div class="menu-item px-3">--}}
{{--                                <a href="#" class="menu-link px-3">New Ticket</a>--}}
{{--                            </div>--}}
{{--                            <!--end::Menu item-->--}}
{{--                            <!--begin::Menu item-->--}}
{{--                            <div class="menu-item px-3">--}}
{{--                                <a href="#" class="menu-link px-3">New Customer</a>--}}
{{--                            </div>--}}
{{--                            <!--end::Menu item-->--}}
{{--                            <!--begin::Menu item-->--}}
{{--                            <div class="menu-item px-3" data-kt-menu-trigger="hover" data-kt-menu-placement="right-start">--}}
{{--                                <!--begin::Menu item-->--}}
{{--                                <a href="#" class="menu-link px-3">--}}
{{--                                    <span class="menu-title">New Group</span>--}}
{{--                                    <span class="menu-arrow"></span>--}}
{{--                                </a>--}}
{{--                                <!--end::Menu item-->--}}
{{--                                <!--begin::Menu sub-->--}}
{{--                                <div class="menu-sub menu-sub-dropdown w-175px py-4">--}}
{{--                                    <!--begin::Menu item-->--}}
{{--                                    <div class="menu-item px-3">--}}
{{--                                        <a href="#" class="menu-link px-3">Admin Group</a>--}}
{{--                                    </div>--}}
{{--                                    <!--end::Menu item-->--}}
{{--                                    <!--begin::Menu item-->--}}
{{--                                    <div class="menu-item px-3">--}}
{{--                                        <a href="#" class="menu-link px-3">Staff Group</a>--}}
{{--                                    </div>--}}
{{--                                    <!--end::Menu item-->--}}
{{--                                    <!--begin::Menu item-->--}}
{{--                                    <div class="menu-item px-3">--}}
{{--                                        <a href="#" class="menu-link px-3">Member Group</a>--}}
{{--                                    </div>--}}
{{--                                    <!--end::Menu item-->--}}
{{--                                </div>--}}
{{--                                <!--end::Menu sub-->--}}
{{--                            </div>--}}
{{--                            <!--end::Menu item-->--}}
{{--                            <!--begin::Menu item-->--}}
{{--                            <div class="menu-item px-3">--}}
{{--                                <a href="#" class="menu-link px-3">New Contact</a>--}}
{{--                            </div>--}}
{{--                            <!--end::Menu item-->--}}
{{--                            <!--begin::Menu separator-->--}}
{{--                            <div class="separator mt-3 opacity-75"></div>--}}
{{--                            <!--end::Menu separator-->--}}
{{--                            <!--begin::Menu item-->--}}
{{--                            <div class="menu-item px-3">--}}
{{--                                <div class="menu-content px-3 py-3">--}}
{{--                                    <a class="btn btn-primary btn-sm px-4" href="#">Generate Reports</a>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            <!--end::Menu item-->--}}
{{--                        </div>--}}
{{--                        <!--end::Menu 2-->--}}
{{--                        <!--end::Menu-->--}}
                    </div>
                </div>
                <!--end::Header-->
                <!--begin::Body-->
                <div class="card-body py-3">
                    <!--begin::Table container-->
                    <div class="table-responsive">
                        <!--begin::Table-->
                        <table class="table table-row-bordered table-row-gray-100 align-middle gs-0 gy-3">
                            <!--begin::Table head-->
                            <thead>
                            <tr class="fw-bolder text-muted">
                                <th class="w-25px">
                                    <div class="form-check form-check-sm form-check-custom form-check-solid">
                                        <input class="form-check-input" type="checkbox" value="1" data-kt-check="true" data-kt-check-target=".widget-13-check" />
                                    </div>
                                </th>
                                <th class="min-w-150px">Title</th>
                                <th class="min-w-100px text-end">Actions</th>
                            </tr>
                            </thead>
                            <!--end::Table head-->
                            <!--begin::Table body-->
                            <tbody>
                            @foreach($villas as $villa)
                                <tr>
                                    <td>
                                        <div class="form-check form-check-sm form-check-custom form-check-solid">
                                            <input class="form-check-input widget-13-check" type="checkbox" value="1" />
                                        </div>
                                    </td>
                                    <td>
                                        <a href="#" class="text-dark fw-bolder text-hover-primary fs-6">{{$villa->name}}</a>
                                    </td>

                                    <td class="text-end">
                                        <a href="#" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1">
                                            <!--begin::Svg Icon | path: icons/duotune/art/art005.svg-->
                                            <span class="svg-icon svg-icon-3">
																	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
																		<path opacity="0.3" d="M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.0825 1.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.9962 6.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.06399 20.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.7934 2.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z" fill="currentColor" />
																		<path d="M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.3789 21.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.696 18.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z" fill="currentColor" />
																	</svg>
																</span>
                                            <!--end::Svg Icon-->
                                        </a>
                                        <a href="#" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm">
                                            <!--begin::Svg Icon | path: icons/duotune/general/gen027.svg-->
                                            <span class="svg-icon svg-icon-3">
																	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
																		<path d="M5 9C5 8.44772 5.44772 8 6 8H18C18.5523 8 19 8.44772 19 9V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V9Z" fill="currentColor" />
																		<path opacity="0.5" d="M5 5C5 4.44772 5.44772 4 6 4H18C18.5523 4 19 4.44772 19 5V5C19 5.55228 18.5523 6 18 6H6C5.44772 6 5 5.55228 5 5V5Z" fill="currentColor" />
																		<path opacity="0.5" d="M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4V4H9V4Z" fill="currentColor" />
																	</svg>
																</span>
                                            <!--end::Svg Icon-->
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <!--end::Table body-->
                        </table>
                        <!--end::Table-->
                    </div>
                    <!--end::Table container-->
                </div>
                <!--begin::Body-->
            </div>
        </div>
    </div>
    <!--end::Post-->
@endsection
@section('page_script')
    <script>

    </script>
@endsection